//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  hero: Hero;
  heroConnection: HeroConnection;
  videobook: Videobook;
  videobookConnection: VideobookConnection;
  galeria: Galeria;
  galeriaConnection: GaleriaConnection;
  conoceme: Conoceme;
  conocemeConnection: ConocemeConnection;
  contacto: Contacto;
  contactoConnection: ContactoConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHeroArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHeroConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeroFilter>;
};


export type QueryVideobookArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryVideobookConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<VideobookFilter>;
};


export type QueryGaleriaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGaleriaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GaleriaFilter>;
};


export type QueryConocemeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConocemeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConocemeFilter>;
};


export type QueryContactoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactoFilter>;
};

export type DocumentFilter = {
  hero?: InputMaybe<HeroFilter>;
  videobook?: InputMaybe<VideobookFilter>;
  galeria?: InputMaybe<GaleriaFilter>;
  conoceme?: InputMaybe<ConocemeFilter>;
  contacto?: InputMaybe<ContactoFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Hero | Videobook | Galeria | Conoceme | Contacto | Folder;

export type HeroSlides = {
  __typename?: 'HeroSlides';
  bg?: Maybe<Scalars['String']['output']>;
  textColor?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type Hero = Node & Document & {
  __typename?: 'Hero';
  quote?: Maybe<Scalars['String']['output']>;
  quoteAttribution?: Maybe<Scalars['String']['output']>;
  slides?: Maybe<Array<Maybe<HeroSlides>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HeroSlidesFilter = {
  bg?: InputMaybe<StringFilter>;
  textColor?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type HeroFilter = {
  quote?: InputMaybe<StringFilter>;
  quoteAttribution?: InputMaybe<StringFilter>;
  slides?: InputMaybe<HeroSlidesFilter>;
};

export type HeroConnectionEdges = {
  __typename?: 'HeroConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Hero>;
};

export type HeroConnection = Connection & {
  __typename?: 'HeroConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HeroConnectionEdges>>>;
};

export type VideobookFeatured = {
  __typename?: 'VideobookFeatured';
  embedUrl?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
};

export type VideobookGrid = {
  __typename?: 'VideobookGrid';
  embedUrl?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
};

export type Videobook = Node & Document & {
  __typename?: 'Videobook';
  featured?: Maybe<VideobookFeatured>;
  grid?: Maybe<Array<Maybe<VideobookGrid>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type VideobookFeaturedFilter = {
  embedUrl?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
};

export type VideobookGridFilter = {
  embedUrl?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
};

export type VideobookFilter = {
  featured?: InputMaybe<VideobookFeaturedFilter>;
  grid?: InputMaybe<VideobookGridFilter>;
};

export type VideobookConnectionEdges = {
  __typename?: 'VideobookConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Videobook>;
};

export type VideobookConnection = Connection & {
  __typename?: 'VideobookConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<VideobookConnectionEdges>>>;
};

export type GaleriaPhotos = {
  __typename?: 'GaleriaPhotos';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type Galeria = Node & Document & {
  __typename?: 'Galeria';
  photos?: Maybe<Array<Maybe<GaleriaPhotos>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GaleriaPhotosFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type GaleriaFilter = {
  photos?: InputMaybe<GaleriaPhotosFilter>;
};

export type GaleriaConnectionEdges = {
  __typename?: 'GaleriaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Galeria>;
};

export type GaleriaConnection = Connection & {
  __typename?: 'GaleriaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GaleriaConnectionEdges>>>;
};

export type Conoceme = Node & Document & {
  __typename?: 'Conoceme';
  portraitSrc?: Maybe<Scalars['String']['output']>;
  portraitAlt?: Maybe<Scalars['String']['output']>;
  heading?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ConocemeFilter = {
  portraitSrc?: InputMaybe<ImageFilter>;
  portraitAlt?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  bio?: InputMaybe<StringFilter>;
};

export type ConocemeConnectionEdges = {
  __typename?: 'ConocemeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Conoceme>;
};

export type ConocemeConnection = Connection & {
  __typename?: 'ConocemeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ConocemeConnectionEdges>>>;
};

export type Contacto = Node & Document & {
  __typename?: 'Contacto';
  backgroundSrc?: Maybe<Scalars['String']['output']>;
  backgroundAlt?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactoFilter = {
  backgroundSrc?: InputMaybe<ImageFilter>;
  backgroundAlt?: InputMaybe<StringFilter>;
};

export type ContactoConnectionEdges = {
  __typename?: 'ContactoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contacto>;
};

export type ContactoConnection = Connection & {
  __typename?: 'ContactoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactoConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHero: Hero;
  createHero: Hero;
  updateVideobook: Videobook;
  createVideobook: Videobook;
  updateGaleria: Galeria;
  createGaleria: Galeria;
  updateConoceme: Conoceme;
  createConoceme: Conoceme;
  updateContacto: Contacto;
  createContacto: Contacto;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HeroMutation;
};


export type MutationCreateHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HeroMutation;
};


export type MutationUpdateVideobookArgs = {
  relativePath: Scalars['String']['input'];
  params: VideobookMutation;
};


export type MutationCreateVideobookArgs = {
  relativePath: Scalars['String']['input'];
  params: VideobookMutation;
};


export type MutationUpdateGaleriaArgs = {
  relativePath: Scalars['String']['input'];
  params: GaleriaMutation;
};


export type MutationCreateGaleriaArgs = {
  relativePath: Scalars['String']['input'];
  params: GaleriaMutation;
};


export type MutationUpdateConocemeArgs = {
  relativePath: Scalars['String']['input'];
  params: ConocemeMutation;
};


export type MutationCreateConocemeArgs = {
  relativePath: Scalars['String']['input'];
  params: ConocemeMutation;
};


export type MutationUpdateContactoArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactoMutation;
};


export type MutationCreateContactoArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactoMutation;
};

export type DocumentUpdateMutation = {
  hero?: InputMaybe<HeroMutation>;
  videobook?: InputMaybe<VideobookMutation>;
  galeria?: InputMaybe<GaleriaMutation>;
  conoceme?: InputMaybe<ConocemeMutation>;
  contacto?: InputMaybe<ContactoMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  hero?: InputMaybe<HeroMutation>;
  videobook?: InputMaybe<VideobookMutation>;
  galeria?: InputMaybe<GaleriaMutation>;
  conoceme?: InputMaybe<ConocemeMutation>;
  contacto?: InputMaybe<ContactoMutation>;
};

export type HeroSlidesMutation = {
  bg?: InputMaybe<Scalars['String']['input']>;
  textColor?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type HeroMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  quoteAttribution?: InputMaybe<Scalars['String']['input']>;
  slides?: InputMaybe<Array<InputMaybe<HeroSlidesMutation>>>;
};

export type VideobookFeaturedMutation = {
  embedUrl?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
};

export type VideobookGridMutation = {
  embedUrl?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
};

export type VideobookMutation = {
  featured?: InputMaybe<VideobookFeaturedMutation>;
  grid?: InputMaybe<Array<InputMaybe<VideobookGridMutation>>>;
};

export type GaleriaPhotosMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type GaleriaMutation = {
  photos?: InputMaybe<Array<InputMaybe<GaleriaPhotosMutation>>>;
};

export type ConocemeMutation = {
  portraitSrc?: InputMaybe<Scalars['String']['input']>;
  portraitAlt?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
};

export type ContactoMutation = {
  backgroundSrc?: InputMaybe<Scalars['String']['input']>;
  backgroundAlt?: InputMaybe<Scalars['String']['input']>;
};

export type HeroPartsFragment = { __typename: 'Hero', quote?: string | null, quoteAttribution?: string | null, slides?: Array<{ __typename: 'HeroSlides', bg?: string | null, textColor?: string | null, image?: string | null } | null> | null };

export type VideobookPartsFragment = { __typename: 'Videobook', featured?: { __typename: 'VideobookFeatured', embedUrl?: string | null, title?: string | null, date?: string | null } | null, grid?: Array<{ __typename: 'VideobookGrid', embedUrl?: string | null, title?: string | null, date?: string | null } | null> | null };

export type GaleriaPartsFragment = { __typename: 'Galeria', photos?: Array<{ __typename: 'GaleriaPhotos', src?: string | null, alt?: string | null } | null> | null };

export type ConocemePartsFragment = { __typename: 'Conoceme', portraitSrc?: string | null, portraitAlt?: string | null, heading?: string | null, bio?: string | null };

export type ContactoPartsFragment = { __typename: 'Contacto', backgroundSrc?: string | null, backgroundAlt?: string | null };

export type HeroQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HeroQuery = { __typename?: 'Query', hero: { __typename: 'Hero', id: string, quote?: string | null, quoteAttribution?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, slides?: Array<{ __typename: 'HeroSlides', bg?: string | null, textColor?: string | null, image?: string | null } | null> | null } };

export type HeroConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeroFilter>;
}>;


export type HeroConnectionQuery = { __typename?: 'Query', heroConnection: { __typename?: 'HeroConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HeroConnectionEdges', cursor: string, node?: { __typename: 'Hero', id: string, quote?: string | null, quoteAttribution?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, slides?: Array<{ __typename: 'HeroSlides', bg?: string | null, textColor?: string | null, image?: string | null } | null> | null } | null } | null> | null } };

export type VideobookQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type VideobookQuery = { __typename?: 'Query', videobook: { __typename: 'Videobook', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, featured?: { __typename: 'VideobookFeatured', embedUrl?: string | null, title?: string | null, date?: string | null } | null, grid?: Array<{ __typename: 'VideobookGrid', embedUrl?: string | null, title?: string | null, date?: string | null } | null> | null } };

export type VideobookConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<VideobookFilter>;
}>;


export type VideobookConnectionQuery = { __typename?: 'Query', videobookConnection: { __typename?: 'VideobookConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'VideobookConnectionEdges', cursor: string, node?: { __typename: 'Videobook', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, featured?: { __typename: 'VideobookFeatured', embedUrl?: string | null, title?: string | null, date?: string | null } | null, grid?: Array<{ __typename: 'VideobookGrid', embedUrl?: string | null, title?: string | null, date?: string | null } | null> | null } | null } | null> | null } };

export type GaleriaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GaleriaQuery = { __typename?: 'Query', galeria: { __typename: 'Galeria', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, photos?: Array<{ __typename: 'GaleriaPhotos', src?: string | null, alt?: string | null } | null> | null } };

export type GaleriaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GaleriaFilter>;
}>;


export type GaleriaConnectionQuery = { __typename?: 'Query', galeriaConnection: { __typename?: 'GaleriaConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GaleriaConnectionEdges', cursor: string, node?: { __typename: 'Galeria', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, photos?: Array<{ __typename: 'GaleriaPhotos', src?: string | null, alt?: string | null } | null> | null } | null } | null> | null } };

export type ConocemeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ConocemeQuery = { __typename?: 'Query', conoceme: { __typename: 'Conoceme', id: string, portraitSrc?: string | null, portraitAlt?: string | null, heading?: string | null, bio?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ConocemeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConocemeFilter>;
}>;


export type ConocemeConnectionQuery = { __typename?: 'Query', conocemeConnection: { __typename?: 'ConocemeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ConocemeConnectionEdges', cursor: string, node?: { __typename: 'Conoceme', id: string, portraitSrc?: string | null, portraitAlt?: string | null, heading?: string | null, bio?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ContactoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactoQuery = { __typename?: 'Query', contacto: { __typename: 'Contacto', id: string, backgroundSrc?: string | null, backgroundAlt?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContactoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactoFilter>;
}>;


export type ContactoConnectionQuery = { __typename?: 'Query', contactoConnection: { __typename?: 'ContactoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactoConnectionEdges', cursor: string, node?: { __typename: 'Contacto', id: string, backgroundSrc?: string | null, backgroundAlt?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HeroPartsFragmentDoc = gql`
    fragment HeroParts on Hero {
  __typename
  quote
  quoteAttribution
  slides {
    __typename
    bg
    textColor
    image
  }
}
    `;
export const VideobookPartsFragmentDoc = gql`
    fragment VideobookParts on Videobook {
  __typename
  featured {
    __typename
    embedUrl
    title
    date
  }
  grid {
    __typename
    embedUrl
    title
    date
  }
}
    `;
export const GaleriaPartsFragmentDoc = gql`
    fragment GaleriaParts on Galeria {
  __typename
  photos {
    __typename
    src
    alt
  }
}
    `;
export const ConocemePartsFragmentDoc = gql`
    fragment ConocemeParts on Conoceme {
  __typename
  portraitSrc
  portraitAlt
  heading
  bio
}
    `;
export const ContactoPartsFragmentDoc = gql`
    fragment ContactoParts on Contacto {
  __typename
  backgroundSrc
  backgroundAlt
}
    `;
export const HeroDocument = gql`
    query hero($relativePath: String!) {
  hero(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HeroParts
  }
}
    ${HeroPartsFragmentDoc}`;
export const HeroConnectionDocument = gql`
    query heroConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HeroFilter) {
  heroConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HeroParts
      }
    }
  }
}
    ${HeroPartsFragmentDoc}`;
export const VideobookDocument = gql`
    query videobook($relativePath: String!) {
  videobook(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...VideobookParts
  }
}
    ${VideobookPartsFragmentDoc}`;
export const VideobookConnectionDocument = gql`
    query videobookConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: VideobookFilter) {
  videobookConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...VideobookParts
      }
    }
  }
}
    ${VideobookPartsFragmentDoc}`;
export const GaleriaDocument = gql`
    query galeria($relativePath: String!) {
  galeria(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GaleriaParts
  }
}
    ${GaleriaPartsFragmentDoc}`;
export const GaleriaConnectionDocument = gql`
    query galeriaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GaleriaFilter) {
  galeriaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GaleriaParts
      }
    }
  }
}
    ${GaleriaPartsFragmentDoc}`;
export const ConocemeDocument = gql`
    query conoceme($relativePath: String!) {
  conoceme(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ConocemeParts
  }
}
    ${ConocemePartsFragmentDoc}`;
export const ConocemeConnectionDocument = gql`
    query conocemeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ConocemeFilter) {
  conocemeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ConocemeParts
      }
    }
  }
}
    ${ConocemePartsFragmentDoc}`;
export const ContactoDocument = gql`
    query contacto($relativePath: String!) {
  contacto(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactoParts
  }
}
    ${ContactoPartsFragmentDoc}`;
export const ContactoConnectionDocument = gql`
    query contactoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactoFilter) {
  contactoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactoParts
      }
    }
  }
}
    ${ContactoPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      hero(variables: HeroQueryVariables, options?: C): Promise<{data: HeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroQueryVariables, query: string}> {
        return requester<{data: HeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroQueryVariables, query: string}, HeroQueryVariables>(HeroDocument, variables, options);
      },
    heroConnection(variables?: HeroConnectionQueryVariables, options?: C): Promise<{data: HeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroConnectionQueryVariables, query: string}> {
        return requester<{data: HeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroConnectionQueryVariables, query: string}, HeroConnectionQueryVariables>(HeroConnectionDocument, variables, options);
      },
    videobook(variables: VideobookQueryVariables, options?: C): Promise<{data: VideobookQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VideobookQueryVariables, query: string}> {
        return requester<{data: VideobookQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VideobookQueryVariables, query: string}, VideobookQueryVariables>(VideobookDocument, variables, options);
      },
    videobookConnection(variables?: VideobookConnectionQueryVariables, options?: C): Promise<{data: VideobookConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VideobookConnectionQueryVariables, query: string}> {
        return requester<{data: VideobookConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VideobookConnectionQueryVariables, query: string}, VideobookConnectionQueryVariables>(VideobookConnectionDocument, variables, options);
      },
    galeria(variables: GaleriaQueryVariables, options?: C): Promise<{data: GaleriaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GaleriaQueryVariables, query: string}> {
        return requester<{data: GaleriaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GaleriaQueryVariables, query: string}, GaleriaQueryVariables>(GaleriaDocument, variables, options);
      },
    galeriaConnection(variables?: GaleriaConnectionQueryVariables, options?: C): Promise<{data: GaleriaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GaleriaConnectionQueryVariables, query: string}> {
        return requester<{data: GaleriaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GaleriaConnectionQueryVariables, query: string}, GaleriaConnectionQueryVariables>(GaleriaConnectionDocument, variables, options);
      },
    conoceme(variables: ConocemeQueryVariables, options?: C): Promise<{data: ConocemeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConocemeQueryVariables, query: string}> {
        return requester<{data: ConocemeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConocemeQueryVariables, query: string}, ConocemeQueryVariables>(ConocemeDocument, variables, options);
      },
    conocemeConnection(variables?: ConocemeConnectionQueryVariables, options?: C): Promise<{data: ConocemeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConocemeConnectionQueryVariables, query: string}> {
        return requester<{data: ConocemeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConocemeConnectionQueryVariables, query: string}, ConocemeConnectionQueryVariables>(ConocemeConnectionDocument, variables, options);
      },
    contacto(variables: ContactoQueryVariables, options?: C): Promise<{data: ContactoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactoQueryVariables, query: string}> {
        return requester<{data: ContactoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactoQueryVariables, query: string}, ContactoQueryVariables>(ContactoDocument, variables, options);
      },
    contactoConnection(variables?: ContactoConnectionQueryVariables, options?: C): Promise<{data: ContactoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactoConnectionQueryVariables, query: string}> {
        return requester<{data: ContactoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactoConnectionQueryVariables, query: string}, ContactoConnectionQueryVariables>(ContactoConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  